### ISSUE TITLE
[Feature request] Setup github actions

### ISSUE THREAD

**Issue by Twig6943** [nlordell/aseprite-appimage#3]
@nlordell I use libresprite but this would help those that use aseprite instead.

**Comment by nlordell** [comment]
Do you mean support something like:

```yaml
jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - uses: nlordell/setup-aseprite@v1
            # - ...
```
